# Generated by Django 5.0.6 on 2025-12-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='school_portal.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_portal.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, to='school_portal.class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_portal.teacher'),
        ),
    ]
