# Generated by Django 5.0.6 on 2025-12-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0003_assignment_coefficient_assignment_evaluation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
