# Generated by Django 5.0.6 on 2025-12-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0004_alter_student_surname_alter_teacher_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('inscription', 'Nouvelle Inscription'), ('reinscription', 'Réinscription')], default='inscription', max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complétée'), ('cancelled', 'Annulée')], default='completed', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('bank', 'Virement Bancaire'), ('mobile', 'Mobile Money'), ('check', 'Chèque')], max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school_portal.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school_portal.student')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-enrollment_date', '-created_at'],
            },
        ),
    ]
