# Generated by Django 5.0.6 on 2025-12-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0005_student_matricule_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
