# Generated by Django 5.0.6 on 2025-12-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0006_alter_enrollment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_classes', to='school_portal.teacher'),
        ),
    ]
