# Generated by Django 5.0.6 on 2025-12-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0007_subjectclass_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'école")),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logo/', verbose_name="Logo de l'école")),
                ('director_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du Directeur')),
                ('motto', models.CharField(blank=True, max_length=300, null=True, verbose_name="Devise de l'école")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Paramètres de l'École",
                'verbose_name_plural': "Paramètres de l'École",
            },
        ),
    ]
