# Generated by Django 5.0.6 on 2025-12-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0010_alter_student_address_alter_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
