# Generated by Django 5.0.6 on 2025-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0011_alter_teacher_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
