# Generated by Django 5.0.6 on 2025-12-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0012_alter_teacher_address_alter_teacher_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='coefficient',
        ),
    ]
