# Generated by Django 5.0.6 on 2025-12-14 15:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Année')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Année active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Année Scolaire',
                'verbose_name_plural': 'Années Scolaires',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du frais')),
                ('category', models.CharField(choices=[('inscription', 'Inscription'), ('reinscription', 'Réinscription'), ('scolarite', 'Scolarité'), ('examen', "Frais d'examen"), ('cantine', 'Cantine'), ('transport', 'Transport'), ('uniforme', 'Uniforme'), ('materiel', 'Matériel scolaire'), ('activite', 'Activités'), ('autre', 'Autres frais')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de Frais',
                'verbose_name_plural': 'Types de Frais',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('method_type', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('check', 'Chèque'), ('card', 'Carte bancaire')], max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mode de Paiement',
                'verbose_name_plural': 'Modes de Paiement',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant total (FCFA)')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant payé (FCFA)')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('period', models.CharField(blank=True, choices=[('trimestre1', 'Trimestre 1'), ('trimestre2', 'Trimestre 2'), ('trimestre3', 'Trimestre 3'), ('semestre1', 'Semestre 1'), ('semestre2', 'Semestre 2'), ('annuel', 'Annuel')], max_length=20, verbose_name='Période')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de référence')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transaction')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiel'), ('completed', 'Complet'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('received_by', models.CharField(blank=True, max_length=100, verbose_name='Reçu par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_finance.academicyear', verbose_name='Année scolaire')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_finance.feetype', verbose_name='Type de frais')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_portal.student', verbose_name='Étudiant')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_finance.paymentmethod', verbose_name='Mode de paiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='Numéro de versement')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('payment_date', models.DateField(verbose_name='Date de versement')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('received_by', models.CharField(blank=True, max_length=100, verbose_name='Reçu par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='school_finance.payment', verbose_name='Paiement')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_finance.paymentmethod', verbose_name='Mode de paiement')),
            ],
            options={
                'verbose_name': 'Versement',
                'verbose_name_plural': 'Versements',
                'ordering': ['payment', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('issued_by', models.CharField(max_length=100, verbose_name='Émis par')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='school_finance.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('new', 'Nouvelle inscription'), ('renewal', 'Réinscription')], max_length=10, verbose_name='Type')),
                ('enrollment_date', models.DateField(verbose_name="Date d'inscription")),
                ('enrollment_fee', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Frais d'inscription (FCFA)")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_finance.academicyear', verbose_name='Année scolaire')),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_portal.class', verbose_name='Classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_portal.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-enrollment_date', '-created_at'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('payment_frequency', models.CharField(choices=[('unique', 'Paiement unique'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='trimestriel', max_length=20, verbose_name='Fréquence')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_finance.academicyear', verbose_name='Année scolaire')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_portal.class', verbose_name='Classe')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_finance.feetype', verbose_name='Type de frais')),
            ],
            options={
                'verbose_name': 'Structure de Frais',
                'verbose_name_plural': 'Structures de Frais',
                'ordering': ['academic_year', 'class_level', 'fee_type'],
                'unique_together': {('academic_year', 'class_level', 'fee_type')},
            },
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total des frais (FCFA)')),
                ('total_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total payé (FCFA)')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Dernier paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_finance.academicyear', verbose_name='Année scolaire')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_portal.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Compte Étudiant',
                'verbose_name_plural': 'Comptes Étudiants',
                'ordering': ['student'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
