# Generated by Django 5.0.6 on 2026-06-03 13:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='school_finance.paymentinstallment', verbose_name='Versement'),
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('trimestre1', 'Trimestre 1'), ('trimestre2', 'Trimestre 2'), ('trimestre3', 'Trimestre 3'), ('semestre1', 'Semestre 1'), ('semestre2', 'Semestre 2')], max_length=20, verbose_name='Période')),
                ('expected_amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant attendu (FCFA)')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school_finance.feestructure', verbose_name='Structure de frais')),
            ],
            options={
                'verbose_name': 'Échéancier',
                'verbose_name_plural': 'Échéanciers',
                'ordering': ['fee_structure', 'period'],
                'unique_together': {('fee_structure', 'period')},
            },
        ),
    ]
